apiVersion: v1
kind: Service
metadata:
  name: devopsdemo-service
spec:
  selector:
    app: devopsdemo-service
  ports:
  - port: 3000
    targetPort: 3000
    name: devopsdemo-service
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdemo-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsdemo-service
  template:
    metadata:
      labels:
        app: devopsdemo-service
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      nodeName: solda
      containers:
        - name: devopsdemo-service
          image: ${CICD_IMAGE}:latest
          envFrom:
            - secretRef:
                name: devopsdemo-dev
                optional: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devopsdemo-ingress
  namespace: dev
spec:
  rules:
    - host: 159.69.34.164.xip.io
      http:
        paths:
          - backend:
              serviceName: devopsdemo-service
              servicePort: 3000
  tls:
    - hosts:
        - 159.69.34.164.xip.io
